name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore: [staging-squash-merge.tmp]
  pull_request:
    branches: [main, staging, trying]
    types: [opened, synchronize, reopened, ready_for_review]

# Cancel previous runs on the same PR.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: e2e
    env:
      MIRRORD_AGENT_RUST_LOG: "warn,mirrord=debug"
      RUST_BACKTRACE: "1"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          key: ubuntu-latest
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.0-rc.3"
      - run: |
          go version
      - run: |
          cd tests/go-e2e-fileops
          go build -o 20
      - name: start minikube
        uses: medyagh/setup-minikube@master
        with:
          container-runtime: containerd
      - name: cargo test
        run: for i in {1..20}; do cargo test -p tests test_file_ops_linux; done
      - name: switch minikube runtime
        run: |
          minikube delete
          minikube start --container-runtime=docker
      - name: test with docker runtime
        run: for i in {1..20}; do cargo test -p tests test_file_ops_linux; done
      - name: Collect logs
        if: ${{ failure() }}
        run: |
          kubectl describe pods
          docker exec minikube find /var/log/pods -print -exec cat {} \;