name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore: [staging-squash-merge.tmp]
  pull_request:
    branches: [main, staging, trying]
    types: [opened, synchronize, reopened, ready_for_review]

# Cancel previous runs on the same PR.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"
  MIRRORD_TELEMETRY: false

jobs:
  build_mirrord:
    runs-on: ubuntu-latest
    name: build mirrord
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: cargo build --manifest-path=./Cargo.toml
      - name: upload layer
        uses: actions/upload-artifact@v3
        with:
          name: mirrord-artifacts
          path: |
            target/debug/libmirrord_layer.so
            target/debug/mirrord
          if-no-files-found: error

  integration_tests:
    runs-on: ubuntu-latest
    needs: build_mirrord
    env:
      MIRRORD_TEST_USE_EXISTING_LIB: /home/runner/work/mirrord/mirrord/target/debug/libmirrord_layer.so
    steps:
      - uses: actions/checkout@v3 # Checkout the mirrord repo.
      - uses: actions-rust-lang/setup-rust-toolchain@v1 # Install rust.
        with:
          target: x86_64-unknown-linux-gnu
      - run: ./scripts/build_c_apps.sh
      - name: download layer # Download layer lib built in the `build_mirrord` job.
        uses: actions/download-artifact@v3
        with:
          name: mirrord-artifacts
          path: target/debug/
      - run: cargo test -p mirrord-layer fork
      - run: cargo test -p mirrord-layer fork
      - run: cargo test -p mirrord-layer fork
      - run: cargo test -p mirrord-layer fork
      - run: cargo test -p mirrord-layer fork
      - run: cargo test -p mirrord-layer fork

  integration_tests_macos:
    runs-on: macos-12
    env:
      MIRRORD_TEST_USE_EXISTING_LIB: ../../target/debug/libmirrord_layer.dylib
      RUST_LOG: warn,mirrord=trace
    steps:
      - uses: actions/checkout@v3 # Checkout the mirrord repo.
      - uses: actions-rust-lang/setup-rust-toolchain@v1 # Install Rust.
        with:
          target: x86_64-apple-darwin
      - run: ./scripts/build_c_apps.sh
      - run: cargo build -p mirrord-layer # Build layer lib. The tests load it into the apps.
      - run: cargo test -p mirrord-layer fork
      - run: cargo test -p mirrord-layer fork
      - run: cargo test -p mirrord-layer fork
      - run: cargo test -p mirrord-layer fork
      - run: cargo test -p mirrord-layer fork
      - run: cargo test -p mirrord-layer fork

