name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore: [staging-squash-merge.tmp]
  pull_request:
    branches: [main, staging, trying]
    types: [opened, synchronize, reopened, ready_for_review]

# Cancel previous runs on the same PR.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"
  MIRRORD_TELEMETRY: false

jobs:
  build_mirrord:
    runs-on: ubuntu-latest
    name: build mirrord
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: cargo build --manifest-path=./Cargo.toml
      - name: upload layer
        uses: actions/upload-artifact@v3
        with:
          name: mirrord-artifacts
          path: |
            target/debug/libmirrord_layer.so
            target/debug/mirrord
          if-no-files-found: error

  integration_tests:
    runs-on: ubuntu-latest
    needs: build_mirrord
    env:
      MIRRORD_TEST_USE_EXISTING_LIB: /home/runner/work/mirrord/mirrord/target/debug/libmirrord_layer.so
    steps:
      - uses: actions/checkout@v3 # Checkout the mirrord repo.
      - uses: actions-rust-lang/setup-rust-toolchain@v1 # Install rust.
        with:
          target: x86_64-unknown-linux-gnu
      - run: |
          cd mirrord/layer/tests/apps/issue1123
          rustc issue1123.rs --out-dir target
      - run: |
          cd mirrord/layer/tests/apps/issue1054
          rustc issue1054.rs --out-dir target
      - run: |
          cd mirrord/layer/tests/apps/issue1458
          rustc issue1458.rs --out-dir target
      - run: |
          cd mirrord/layer/tests/apps/issue1458portnot53
          rustc issue1458portnot53.rs --out-dir target
      - uses: actions/setup-node@v3 # For http mirroring test.
        with:
          node-version: 14
      - run: npm install express # For http mirroring test with node.
      - uses: actions/setup-python@v3 # For http mirroring tests with Flask and FastAPI.
      - run: pip3 install flask # For http mirroring test with Flask.
      - run: pip3 install fastapi # For http mirroring test with FastAPI.
      - run: pip3 install uvicorn[standard] # For http mirroring test with FastAPI.
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.0-rc.3"
      - run: |
          go version
      - run: | # Build Go test apps.
          ./scripts/build_go_apps.sh 20
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.5"
      - run: |
          go version
      - run: | # Build Go test apps.
          ./scripts/build_go_apps.sh 19
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18.10"
      - run: |
          go version
      - run: | # Build Go test apps.
          ./scripts/build_go_apps.sh 18
      - run: |
          cd mirrord/layer/tests/apps/fileops
          cargo build
      - run: |
          cd mirrord/layer/tests/apps/outgoing
          cargo build
      - run: |
          cd mirrord/layer/tests/apps/recv_from
          cargo build
      - run: |
          cd mirrord/layer/tests/apps/dns_resolve
          cargo build
      - run: |
          cd mirrord/layer/tests/apps/listen_ports
          cargo build
      - run: ./scripts/build_c_apps.sh
      - name: download layer # Download layer lib built in the `build_mirrord` job.
        uses: actions/download-artifact@v3
        with:
          name: mirrord-artifacts
          path: target/debug/
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
      - run: cargo test -p mirrord-layer
